% Erzeuge PKM mit EE-FG 3T2R

% Moritz Schappler, moritz.schappler@imes.uni-hannover.de, 2020-03
% (C) Institut für Mechatronische Systeme, Leibniz Universität Hannover

clear

settings = struct( ...
  'check_existing', true, ...
  'check_missing', true, ...
  'EE_FG_Nr', 4, ... % 3T2R
  'dryrun', false, ...
  'whitelist_SerialKin', {'S5RPRRR8V1'}, ... % S5RPRRR8V1
  'parcomp_mexcompile', 0, ...
  'parcomp_structsynth', 0, ...
  'base_couplings', 9, ...
  'plf_couplings', 8, ...
  'max_actuation_idx', 4); % Jedes außer letztes Gelenk angetrieben
  
parroblib_add_robots_symact