% Erzeuge PKM mit EE-FG 3T3R die nicht voll-parallel sind

% Moritz Schappler, moritz.schappler@imes.uni-hannover.de, 2025-02
% (C) Institut für Mechatronische Systeme, Universität Hannover

clear

settings = struct( ...
  'EE_FG', logical([1 1 1 1 1 1]), ... % 3T3R
  'onlyspherical', false, ... % Allgemeine Beinketten
  'fullyparallel', false, ...
  'check_existing', true, ...
  'whitelist_SerialKin', {{'S6RRRRRR8V2'}}, ...
  'parcomp_structsynth', 0, ...
  'parcomp_mexcompile', 0, ...
  'base_couplings', 4, ...
  'plf_couplings', 2, ...
  'dryrun', false); 
  
parroblib_add_robots_symact(settings);
