% Erzeuge PKM mit EE-FG 3T2R

% Moritz Schappler, moritz.schappler@imes.uni-hannover.de, 2020-03
% (C) Institut für Mechatronische Systeme, Leibniz Universität Hannover

clc
clear

% Siehe parroblib_update_csv
parroblibpath=fileparts(which('parroblib_path_init.m'));
restab1=readtable(fullfile(parroblibpath, 'synthesis_result_lists', '3T2R.csv'));
restab2=readtable(fullfile(parroblibpath, 'synthesis_result_lists', '3T2R_var.csv'));
restab=[restab1;restab2];
for i = 0:8
  fprintf('3T2R-PKM mit Status %d: %d\n', i, sum(restab.Status==i));
end
fprintf('Insgesamt %d 3T2R-PKM mit gültiger Aktuierung\n', sum(restab.Anzahl_Akt));

settings = struct( ...
  'check_existing', true, ...
  'check_missing', true, ...
  'EE_FG_Nr', 4, ... % 3T2R
  'dryrun', false, ...
  'comp_cluster', true, ...
  'offline', false, ...
  ...'whitelist_SerialKin', {'S5RPRRR2'}, ... % S5RPRRR8V1
  ...'parcomp_mexcompile', 0, ...
  ...'parcomp_structsynth', 0, ...
  ...'base_couplings', 1, ...
  ...'plf_couplings', 8, ...
  'check_resstatus', 4:8, ...
  'max_actuation_idx', 4); % Jedes außer letztes Gelenk angetrieben
  
parroblib_add_robots_symact(settings);